### PR TITLE
<object> tag now has an id.

### PR DESCRIPTION
**Pull request by zippy1981**
This solves google issue 546 http://code.google.com/p/nyromodal/issues/detail?id=546

### CODE REVIEW

**Comment by nyroDev** [comment]
nyroModal v2 is fully stackable. Which means there could be more than one nyroModal open at the same time. Setting an id directly in the code as you did might cause problem becaus ethe same id "nyroModalSwf" will exists multiple time if 2 or more nyroModal containing swf are opened.

An other id might be to set this id regarder the opener by using an attribute or something else.

By the way, the nyromodal.complete will disapear from github. Please use the specific js for the filter to edit it.

Thanks for your pull request anyway!

**Comment by zippy1981** [comment]
Its really awesome that you make the containers stackable. I actually edited the original file as well as the complete one, but I guess I did not commit it.

Not having an id in an <object> causes flash not to be able to call javascript in IE, so there is a need for object elements to have ids. Would you prefer a patch where a unique id was always specified or one where the user could specify having one?

Also, if I gave a patch to add a static id to the google code version of nyroModal, would you accept that? I don't see a code repository for that version.

**Comment by nyroDev** [comment]
nyroModal v1 hosted on google code won't be updated anymore I guess.

regarding your 2 propositions, I thinks a mixed solution would be great :
- Let the ability for the user to manually set the id (with an attribute of the opener or anything you want)
- if not manually set, add an uniq id

It could be great ;)

**Comment by nyroDev** [comment]
Update documentation in Readme file
Add swfObjectId settings and use it in filters.swf or create an uniq ID. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add recalc settings for nm.resize function to force the recalculation of the modal. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix issue with jQuery 1.5 on IE8 (bogus selector in filters.swf). Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix stack error when reopening a modal. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add initFilters callbacks in order to force filters. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closes#37
Add afterReposition and afterUnreposition callbacks.

**Pull request closed without merging**
